### ISSUE TITLE
Redmine repository configuration problem

### ISSUE THREAD

**Issue by boki69** [9506hqwy/redmine_scm_gitlab#1]
Hi,

I'm interested in your plugin.
I installed on my Redmine instance and it was successfull.

My environment:

> 
> 
> Environment:
>   Redmine version                5.0.0.stable
>   Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-linux-gnu]
>   Rails version                  6.1.4.7
>   Environment                    production
>   Database adapter               Mysql2
>   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
>   Mailer delivery                smtp
> Redmine settings:
>   Redmine theme                  Default
> SCM:
>   Subversion                     1.13.0
>   Mercurial                      5.3.1
>   Cvs                            1.12.13
>   Git                            2.25.1
>   Filesystem                     
>   GitLab                         0.1.0

But on project reposiítory settings, I can't set GITLAB type repo.

![kép](https://github.com/9506hqwy/redmine_scm_gitlab/assets/3695756/290daec2-a4b2-4069-ac87-ad8dce1f47d6)

Is this correct?

If it is correct, please describe an example of settings.

Best Regards!

**Comment by 9506hqwy** [comment]
Thank for reporting.

Please confirm that `GitLab`  is enabled on Redmine repository setting.

`Administration->Settings->Repositories->Enabled SCM`

![a](https://github.com/9506hqwy/redmine_scm_gitlab/assets/97424592/b2679201-a602-488f-9358-1fdf3b28966f)

**Comment by boki69** [comment]
Thanks for your help and this great plugin! 

it's working for me, after your suggestion.
